package web

import "strings"

const defaultCharacterColorClass = "text-brand-accent"

var characterColorClassByName = map[string]string{
	"twilight sparkle":      "text-violet-600",
	"rainbow dash":          "text-sky-600",
	"pinkie pie":            "text-pink-500",
	"applejack":             "text-orange-600",
	"rarity":                "text-indigo-500",
	"fluttershy":            "text-amber-500",
	"spike":                 "text-emerald-600",
	"princess celestia":     "text-rose-400",
	"princess luna":         "text-blue-600",
	"princess cadence":      "text-fuchsia-400",
	"shining armor":         "text-blue-500",
	"starlight glimmer":     "text-fuchsia-600",
	"sunset shimmer":        "text-red-500",
	"trixie":                "text-cyan-600",
	"discord":               "text-lime-600",
	"big macintosh":         "text-red-700",
	"big mac":               "text-red-700",
	"granny smith":          "text-green-700",
	"apple bloom":           "text-rose-500",
	"sweetie belle":         "text-purple-500",
	"scootaloo":             "text-orange-500",
	"diamond tiara":         "text-pink-600",
	"silver spoon":          "text-slate-500",
	"babs seed":             "text-red-600",
	"zipporwhill":           "text-cyan-500",
	"pip squeak":            "text-amber-600",
	"twist":                 "text-emerald-500",
	"cozy glow":             "text-red-600",
	"lyra heartstrings":     "text-teal-500",
	"bon bon":               "text-amber-400",
	"derpy":                 "text-yellow-500",
	"doctor whooves":        "text-amber-700",
	"octavia":               "text-slate-700",
	"vinyl scratch":         "text-cyan-500",
	"dj pon-3":              "text-cyan-500",
	"zecora":                "text-emerald-700",
	"cheerilee":             "text-purple-600",
	"photo finish":          "text-indigo-600",
	"fancy pants":           "text-blue-700",
	"soarin":                "text-sky-500",
	"spitfire":              "text-amber-600",
	"fleetfoot":             "text-sky-400",
	"thunderlane":           "text-slate-600",
	"daring do":             "text-yellow-600",
	"bulk biceps":           "text-lime-600",
	"party favor":           "text-fuchsia-500",
	"sugar belle":           "text-rose-500",
	"night glider":          "text-purple-700",
	"double diamond":        "text-cyan-400",
	"trouble shoes":         "text-orange-700",
	"flim":                  "text-yellow-600",
	"flam":                  "text-yellow-700",
	"maud pie":              "text-slate-600",
	"cheese sandwich":       "text-yellow-500",
	"limestone pie":         "text-stone-700",
	"marble pie":            "text-zinc-500",
	"tempest shadow":        "text-purple-700",
	"fizzlepop berrytwist":  "text-purple-700",
	"king sombra":           "text-slate-800",
	"nightmare moon":        "text-indigo-800",
	"queen chrysalis":       "text-emerald-800",
	"tirek":                 "text-red-800",
	"storm king":            "text-slate-700",
	"thorax":                "text-emerald-500",
	"ember":                 "text-amber-600",
	"smolder":               "text-red-500",
	"gallus":                "text-blue-500",
	"yona":                  "text-rose-600",
	"silverstream":          "text-teal-400",
	"ocellus":               "text-lime-500",
	"sandbar":               "text-yellow-600",
	"princess amorenza":     "text-pink-300",
	"prince blueblood":      "text-blue-200",
	"braeburn":              "text-yellow-600",
	"lightning dust":        "text-teal-400",
	"coco pommel":           "text-cyan-200",
	"tree hugger":           "text-lime-500",
	"moondancer":            "text-violet-500",
	"vapor trail":           "text-sky-200",
	"sky stinger":           "text-blue-500",
	"coloratura":            "text-indigo-700",
	"raara":                 "text-indigo-700",
	"adagio dazzle":         "text-orange-700",
	"aria blaze":            "text-purple-800",
	"sonata dusk":           "text-blue-500",
	"daybreaker":            "text-orange-400",
	"chrysalis":             "text-emerald-900",
	"lord tirek":            "text-red-900",
	"grogar":                "text-blue-900",
	"cosmos":                "text-fuchsia-900",
	"starswirl the bearded": "text-slate-500",
	"rockhoof":              "text-orange-800",
	"mistmane":              "text-teal-300",
	"flash magnus":          "text-red-500",
	"somnambula":            "text-yellow-500",
	"meadowbrook":           "text-rose-600",
	"stygian":               "text-slate-700",
}

func characterColorClass(name string) string {
	key := strings.ToLower(strings.TrimSpace(name))
	if className, ok := characterColorClassByName[key]; ok {
		return className
	}
	return defaultCharacterColorClass
}
